/* Comments are generated by ChatGPT for future references */

// Import the React library to create React components
import React from 'react';

// Import the CSS module for styling (assuming it's in the same directory)
import styles from './GoogleButton.module.css';

// Import the Image component from the 'next/image' module
import Image from 'next/image';

// Define a functional React component named GoogleButton
const GoogleButton: React.FC = () => {
    return (
        // Start rendering a button element with a CSS class from the imported module
        <button className={styles.styledGoogle}>
            {/* Render an Image component with the specified properties */}
            <Image src='/google-logo.png' alt='Google Logo' height={35} width={35} />
            {/* Render a paragraph with the text "Sign In with Google" */}
            <p>Sign In with Google</p>
        </button>
    );
}

// Export the GoogleButton component as the default export of this module
export default GoogleButton;
